/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/*import Clases.USuariosControl;*/
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author JEFFERSON
 */
public class FormAdmSistema extends javax.swing.JFrame {

    /*USuariosControl usu = new USuariosControl();*/

    /**
     * Creates new form FormAdmSistema
     */
    public FormAdmSistema() {
        initComponents();
        /*txtIdUs.setEnabled(false);
        txtFeUsu.setEnabled(false);
        
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        jTabbedPane1.setVisible(false);*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRecursosAdm = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCerrarSessionUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPanUsuarios = new javax.swing.JButton();
        txtNombreAdministrador = new javax.swing.JLabel();
        btnSueldoUsuario = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTabbedPaneAdministrador = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdUs = new javax.swing.JTextField();
        txtNomUs = new javax.swing.JTextField();
        txtCorUs = new javax.swing.JTextField();
        txtUsUs = new javax.swing.JTextField();
        txtPasUs = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsrs = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtApUs = new javax.swing.JTextField();
        txtCelUs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFeUsu = new javax.swing.JTextField();
        jtxdniUsuarios = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cbxBusUs = new javax.swing.JComboBox<>();
        txtBUs = new javax.swing.JTextField();
        btnBusUs = new javax.swing.JButton();
        btnRestaurarTablaUsuario = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnAgUs = new javax.swing.JButton();
        btbModUs = new javax.swing.JButton();
        btnResUs = new javax.swing.JButton();
        btnElUs = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblUsuarioSueldos = new javax.swing.JTable();
        jtxSueldoMensUsur = new javax.swing.JTextField();
        jtxCantAutosVenUsu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxBonificacionUsuario = new javax.swing.JTextField();
        txtSueldoTotal = new javax.swing.JTextField();
        jtxPrecioAdicionalUsu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxIDsueldoFacturaUsuar = new javax.swing.JTextField();
        jlabIDusuario = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        rdbAdmUsuarioSueldo = new javax.swing.JRadioButton();
        rdbEmpUsuarioSueldo = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        cbxBuscarDetallePagoUs = new javax.swing.JComboBox<>();
        txtBuscarSelecionPagoUs = new javax.swing.JTextField();
        btnBuscarDetallePagoUsuario = new javax.swing.JButton();
        btnRestauraDetallePagoUs = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnModificarSueldoUs = new javax.swing.JButton();
        btnLimpiarSueldoUs = new javax.swing.JButton();
        btnEliminarSueldoUs = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        btnAgregarSueldoUsu = new javax.swing.JButton();
        jtxtDniAgregarSueldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRecursosAdm.setBackground(new java.awt.Color(153, 255, 255));
        btnRecursosAdm.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRecursosAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/report.png"))); // NOI18N
        btnRecursosAdm.setText("Recursos");
        btnRecursosAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursosAdmActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecursosAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, 47));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSessionUsuario.setBackground(new java.awt.Color(153, 153, 153));
        btnCerrarSessionUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCerrarSessionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir_1.png"))); // NOI18N
        btnCerrarSessionUsuario.setText("Cerrar Sesión");
        btnCerrarSessionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSessionUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSessionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 180, 56));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 525, 260, 140));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanUsuarios.setBackground(new java.awt.Color(153, 255, 255));
        btnPanUsuarios.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPanUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N
        btnPanUsuarios.setText("Usuarios");
        btnPanUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanUsuariosActionPerformed(evt);
            }
        });
        jPanel3.add(btnPanUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, 45));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 190));

        txtNombreAdministrador.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        txtNombreAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreAdministrador.setText("usuario");
        jPanel1.add(txtNombreAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, -1));

        btnSueldoUsuario.setBackground(new java.awt.Color(153, 255, 255));
        btnSueldoUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSueldoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        btnSueldoUsuario.setText("Pagos");
        btnSueldoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueldoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnSueldoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 260, 660));

        jPanel8.setBackground(new java.awt.Color(204, 0, 0));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user1_1.png"))); // NOI18N
        jLabel19.setText("jLabel19");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 190));

        jPanel4.setBackground(new java.awt.Color(204, 102, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1142, 740));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Id:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 36, 25, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 94, 59, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Correo:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 255, 59, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Usuario:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 359, 59, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 411, 76, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Rol:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 463, 59, -1));

        txtIdUs.setForeground(new java.awt.Color(255, 255, 255));
        txtIdUs.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel4.add(txtIdUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 34, 45, -1));

        txtNomUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomUsActionPerformed(evt);
            }
        });
        jPanel4.add(txtNomUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 91, 165, -1));
        jPanel4.add(txtCorUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, 165, -1));
        jPanel4.add(txtUsUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 356, 165, -1));
        jPanel4.add(txtPasUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 408, 165, -1));

        cbxRol.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "Administrador", "Empleado" }));
        jPanel4.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 460, -1, -1));

        jtbUsrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbUsrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUsrsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUsrs);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 111, 870, 466));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Apellido:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 148, 59, -1));
        jPanel4.add(txtApUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 145, 165, -1));
        jPanel4.add(txtCelUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 304, 165, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setText("Teléfono:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 307, 59, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setText("Fecha:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 36, 43, -1));
        jPanel4.add(txtFeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 33, 73, -1));
        jPanel4.add(jtxdniUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 199, 165, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel20.setText("DNI:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 202, 43, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        cbxBusUs.setBackground(new java.awt.Color(153, 153, 153));
        cbxBusUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxBusUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID", "DNI", "Rol" }));

        btnBusUs.setBackground(new java.awt.Color(153, 255, 255));
        btnBusUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBusUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBusUs.setText("Buscar");
        btnBusUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusUsActionPerformed(evt);
            }
        });

        btnRestaurarTablaUsuario.setBackground(new java.awt.Color(204, 153, 255));
        btnRestaurarTablaUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestaurarTablaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestaurarTablaUsuario.setText("Restaurar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cbxBusUs, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(txtBUs, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnBusUs, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRestaurarTablaUsuario)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxBusUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestaurarTablaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 660, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgUs.setBackground(new java.awt.Color(255, 51, 51));
        btnAgUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAgUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnAgUs.setText("Registrar");
        btnAgUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgUsActionPerformed(evt);
            }
        });
        jPanel11.add(btnAgUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        btbModUs.setBackground(new java.awt.Color(102, 255, 51));
        btbModUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btbModUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btbModUs.setText("Modificar");
        btbModUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbModUsActionPerformed(evt);
            }
        });
        jPanel11.add(btbModUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, -1));

        btnResUs.setBackground(new java.awt.Color(255, 255, 51));
        btnResUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnResUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnResUs.setText("Restaurar");
        btnResUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResUsActionPerformed(evt);
            }
        });
        jPanel11.add(btnResUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 28));

        btnElUs.setBackground(new java.awt.Color(153, 0, 204));
        btnElUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnElUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnElUs.setText("Eliminar");
        btnElUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElUsActionPerformed(evt);
            }
        });
        jPanel11.add(btnElUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 290, 90));

        jTabbedPaneAdministrador.addTab("Pestaña Usuarios", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblUsuarioSueldos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblUsuarioSueldos);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 1062, 330));
        jPanel5.add(jtxSueldoMensUsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 518, 90, -1));
        jPanel5.add(jtxCantAutosVenUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 518, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Cantidad de Servicio");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 490, 121, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Bonificación:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 85, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setText("Sueldo Mensual:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 490, 96, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setText("Sueldo Total:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 490, 84, -1));
        jPanel5.add(jtxBonificacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 518, 90, -1));
        jPanel5.add(txtSueldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 518, 100, -1));
        jPanel5.add(jtxPrecioAdicionalUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 518, 100, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setText("Precio/Adicional");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 490, 101, -1));
        jPanel5.add(jtxIDsueldoFacturaUsuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 41, -1));

        jlabIDusuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlabIDusuario.setText("ID:");
        jPanel5.add(jlabIDusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 43, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbAdmUsuarioSueldo.setBackground(new java.awt.Color(153, 153, 153));
        btnGrupo.add(rdbAdmUsuarioSueldo);
        rdbAdmUsuarioSueldo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rdbAdmUsuarioSueldo.setText("Administrador");
        jPanel9.add(rdbAdmUsuarioSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 117, -1));

        rdbEmpUsuarioSueldo.setBackground(new java.awt.Color(153, 153, 153));
        btnGrupo.add(rdbEmpUsuarioSueldo);
        rdbEmpUsuarioSueldo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rdbEmpUsuarioSueldo.setText("Empleado");
        jPanel9.add(rdbEmpUsuarioSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 98, 20));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 240, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        cbxBuscarDetallePagoUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxBuscarDetallePagoUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID Pago", "Nombre", "DNI", "Fecha" }));

        btnBuscarDetallePagoUsuario.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscarDetallePagoUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarDetallePagoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarDetallePagoUsuario.setText("Buscar");

        btnRestauraDetallePagoUs.setBackground(new java.awt.Color(102, 255, 204));
        btnRestauraDetallePagoUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestauraDetallePagoUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestauraDetallePagoUs.setText("Restaurar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cbxBuscarDetallePagoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarSelecionPagoUs, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnBuscarDetallePagoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRestauraDetallePagoUs)
                .addGap(35, 35, 35))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarSelecionPagoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDetallePagoUsuario)
                    .addComponent(cbxBuscarDetallePagoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestauraDetallePagoUs))
                .addGap(15, 15, 15))
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 630, -1));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        btnModificarSueldoUs.setBackground(new java.awt.Color(0, 255, 0));
        btnModificarSueldoUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModificarSueldoUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarSueldoUs.setText("Modificar");

        btnLimpiarSueldoUs.setBackground(new java.awt.Color(255, 255, 51));
        btnLimpiarSueldoUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimpiarSueldoUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnLimpiarSueldoUs.setText("Limpiar");

        btnEliminarSueldoUs.setBackground(new java.awt.Color(204, 102, 255));
        btnEliminarSueldoUs.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarSueldoUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarSueldoUs.setText("Eliminar");
        btnEliminarSueldoUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSueldoUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnModificarSueldoUs)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarSueldoUs, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarSueldoUs)
                .addGap(90, 90, 90))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarSueldoUs)
                    .addComponent(btnEliminarSueldoUs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarSueldoUs)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 300, -1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarSueldoUsu.setBackground(new java.awt.Color(255, 0, 0));
        btnAgregarSueldoUsu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAgregarSueldoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/serv.png"))); // NOI18N
        btnAgregarSueldoUsu.setText("Agregar");
        btnAgregarSueldoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSueldoUsuActionPerformed(evt);
            }
        });
        jPanel14.add(btnAgregarSueldoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 6, -1, 26));
        jPanel14.add(jtxtDniAgregarSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("DNI");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jTabbedPaneAdministrador.addTab("Pestaña Pagos", jPanel5);

        getContentPane().add(jTabbedPaneAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 1290, 660));

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bAN.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1290, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarTablaUsuarios() {
        jtbUsrs.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtbUsrs.getColumnModel().getColumn(0).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtbUsrs.getColumnModel().getColumn(1).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtbUsrs.getColumnModel().getColumn(2).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(3).setPreferredWidth(160);
        jtbUsrs.getColumnModel().getColumn(3).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(4).setPreferredWidth(90);
        jtbUsrs.getColumnModel().getColumn(4).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(5).setPreferredWidth(100);
        jtbUsrs.getColumnModel().getColumn(5).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(6).setPreferredWidth(150);
        jtbUsrs.getColumnModel().getColumn(6).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(7).setPreferredWidth(90);
        jtbUsrs.getColumnModel().getColumn(7).setResizable(false);
        jtbUsrs.getColumnModel().getColumn(8).setPreferredWidth(75);
        jtbUsrs.getColumnModel().getColumn(8).setResizable(false);
        
    }
    private void btnPanUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanUsuariosActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btnPanUsuariosActionPerformed

    private void btnCerrarSessionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSessionUsuarioActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnCerrarSessionUsuarioActionPerformed

    private void btnRecursosAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursosAdmActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRecursosAdmActionPerformed

    private void btnElUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElUsActionPerformed

    private void btnResUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResUsActionPerformed

    private void btbModUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbModUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbModUsActionPerformed

    private void btnAgUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgUsActionPerformed

    private void btnBusUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusUsActionPerformed

    private void jtbUsrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUsrsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbUsrsMouseClicked

    private void txtNomUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomUsActionPerformed

    private void btnSueldoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueldoUsuarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSueldoUsuarioActionPerformed

    private void btnAgregarSueldoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSueldoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarSueldoUsuActionPerformed

    private void btnEliminarSueldoUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSueldoUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSueldoUsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormAdmSistema().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btbModUs;
    public javax.swing.JButton btnAgUs;
    public javax.swing.JButton btnAgregarSueldoUsu;
    public javax.swing.JButton btnBusUs;
    public javax.swing.JButton btnBuscarDetallePagoUsuario;
    public javax.swing.JButton btnCerrarSessionUsuario;
    public javax.swing.JButton btnElUs;
    public javax.swing.JButton btnEliminarSueldoUs;
    public javax.swing.ButtonGroup btnGrupo;
    public javax.swing.JButton btnLimpiarSueldoUs;
    public javax.swing.JButton btnModificarSueldoUs;
    public javax.swing.JButton btnPanUsuarios;
    public javax.swing.JButton btnRecursosAdm;
    public javax.swing.JButton btnResUs;
    public javax.swing.JButton btnRestauraDetallePagoUs;
    public javax.swing.JButton btnRestaurarTablaUsuario;
    public javax.swing.JButton btnSueldoUsuario;
    public javax.swing.JComboBox<String> cbxBusUs;
    public javax.swing.JComboBox<String> cbxBuscarDetallePagoUs;
    public javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPaneAdministrador;
    public javax.swing.JLabel jlabIDusuario;
    public javax.swing.JTable jtbUsrs;
    public javax.swing.JTable jtblUsuarioSueldos;
    public javax.swing.JTextField jtxBonificacionUsuario;
    public javax.swing.JTextField jtxCantAutosVenUsu;
    public javax.swing.JTextField jtxIDsueldoFacturaUsuar;
    public javax.swing.JTextField jtxPrecioAdicionalUsu;
    public javax.swing.JTextField jtxSueldoMensUsur;
    public javax.swing.JTextField jtxdniUsuarios;
    public javax.swing.JTextField jtxtDniAgregarSueldo;
    public javax.swing.JRadioButton rdbAdmUsuarioSueldo;
    public javax.swing.JRadioButton rdbEmpUsuarioSueldo;
    public javax.swing.JTextField txtApUs;
    public javax.swing.JTextField txtBUs;
    public javax.swing.JTextField txtBuscarSelecionPagoUs;
    public javax.swing.JTextField txtCelUs;
    public javax.swing.JTextField txtCorUs;
    public javax.swing.JTextField txtFeUsu;
    public javax.swing.JTextField txtIdUs;
    public javax.swing.JTextField txtNomUs;
    public javax.swing.JLabel txtNombreAdministrador;
    public javax.swing.JPasswordField txtPasUs;
    public javax.swing.JTextField txtSueldoTotal;
    public javax.swing.JTextField txtUsUs;
    // End of variables declaration//GEN-END:variables
}
