/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author JEFFERSON
 */
public class FormEmpSistema extends javax.swing.JFrame {

    /**
     * Creates new form FormEmpSistema
     */
    public FormEmpSistema() {
        initComponents();
        /*this.setSize(new Dimension(400, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");*/
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPaneSistema = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jtxNombreEmpleado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCliente = new javax.swing.JMenu();
        mnGestionarCliente = new javax.swing.JMenuItem();
        mnGestionVehiculo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnGestionServicios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnGestionProducto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnGestionarFactura = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnReporteClienteVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnSalirPanel = new javax.swing.JMenuItem();
        mnVolverPanel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dskPaneSistema.setBackground(new java.awt.Color(102, 255, 204));
        dskPaneSistema.setPreferredSize(new java.awt.Dimension(1600, 1200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtxNombreEmpleado.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jtxNombreEmpleado.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jtxNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jtxNombreEmpleado)
                .addGap(15, 15, 15))
        );

        dskPaneSistema.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskPaneSistemaLayout = new javax.swing.GroupLayout(dskPaneSistema);
        dskPaneSistema.setLayout(dskPaneSistemaLayout);
        dskPaneSistemaLayout.setHorizontalGroup(
            dskPaneSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPaneSistemaLayout.createSequentialGroup()
                .addGap(0, 1100, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dskPaneSistemaLayout.setVerticalGroup(
            dskPaneSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPaneSistemaLayout.createSequentialGroup()
                .addGap(0, 611, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnCliente.setBackground(new java.awt.Color(204, 255, 51));
        mnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cli2.png"))); // NOI18N
        mnCliente.setText("Clientes");
        mnCliente.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        mnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnClienteMouseClicked(evt);
            }
        });

        mnGestionarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGestionarCliente.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnGestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cli1.png"))); // NOI18N
        mnGestionarCliente.setText("Gestionar Cliente");
        mnGestionarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnGestionarClienteMouseClicked(evt);
            }
        });
        mnGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestionarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnGestionarCliente);

        mnGestionVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGestionVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnGestionVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/auto.png"))); // NOI18N
        mnGestionVehiculo.setText("Gestionar Vehículos");
        mnGestionVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestionVehiculoActionPerformed(evt);
            }
        });
        mnCliente.add(mnGestionVehiculo);

        jMenuBar1.add(mnCliente);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/serv4.png"))); // NOI18N
        jMenu2.setText("Servicios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N

        mnGestionServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGestionServicios.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnGestionServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/serv5.png"))); // NOI18N
        mnGestionServicios.setText("Administrar Servicios");
        mnGestionServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestionServiciosActionPerformed(evt);
            }
        });
        jMenu2.add(mnGestionServicios);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PROD4.png"))); // NOI18N
        jMenu1.setText("Categoria");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N

        mnGestionProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGestionProducto.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnGestionProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/prod2.png"))); // NOI18N
        mnGestionProducto.setText("Gestionar Productos");
        jMenu1.add(mnGestionProducto);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/venta_1.png"))); // NOI18N
        jMenu4.setText("Ventas");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });

        mnGestionarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnGestionarFactura.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnGestionarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/vent2.png"))); // NOI18N
        mnGestionarFactura.setText("Nueva Venta");
        mnGestionarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGestionarFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(mnGestionarFactura);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/vre.png"))); // NOI18N
        jMenu3.setText("Reporte De Ventas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N

        mnReporteClienteVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnReporteClienteVentas.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnReporteClienteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/repo2.png"))); // NOI18N
        mnReporteClienteVentas.setText("Reporte Clientes");
        mnReporteClienteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReporteClienteVentasActionPerformed(evt);
            }
        });
        jMenu3.add(mnReporteClienteVentas);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CONFIG_1.png"))); // NOI18N
        jMenu6.setText("Configuración");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N

        mnSalirPanel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnSalirPanel.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnSalirPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CERRAR.png"))); // NOI18N
        mnSalirPanel.setText("Salir");
        mnSalirPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirPanelActionPerformed(evt);
            }
        });
        jMenu6.add(mnSalirPanel);

        mnVolverPanel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnVolverPanel.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mnVolverPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/VOL3.png"))); // NOI18N
        mnVolverPanel.setText("Volver");
        mnVolverPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVolverPanelActionPerformed(evt);
            }
        });
        jMenu6.add(mnVolverPanel);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu4MenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuDeselected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuDeselected

    private void mnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnClienteMouseClicked

    private void mnGestionarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnGestionarClienteMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mnGestionarClienteMouseClicked

    private void mnGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestionarClienteActionPerformed
        // TODO add your handling code here:
          
        
    }//GEN-LAST:event_mnGestionarClienteActionPerformed

    private void mnSalirPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirPanelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnSalirPanelActionPerformed

    private void mnVolverPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVolverPanelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnVolverPanelActionPerformed

    private void mnGestionVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestionVehiculoActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_mnGestionVehiculoActionPerformed

    private void mnGestionServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestionServiciosActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_mnGestionServiciosActionPerformed

    private void mnGestionarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGestionarFacturaActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_mnGestionarFacturaActionPerformed

    private void mnReporteClienteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReporteClienteVentasActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_mnReporteClienteVentasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormEmpSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormEmpSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormEmpSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormEmpSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormEmpSistema().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dskPaneSistema;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jtxNombreEmpleado;
    public javax.swing.JMenu mnCliente;
    public javax.swing.JMenuItem mnGestionProducto;
    public javax.swing.JMenuItem mnGestionServicios;
    public javax.swing.JMenuItem mnGestionVehiculo;
    public javax.swing.JMenuItem mnGestionarCliente;
    public javax.swing.JMenuItem mnGestionarFactura;
    public javax.swing.JMenuItem mnReporteClienteVentas;
    public javax.swing.JMenuItem mnSalirPanel;
    public javax.swing.JMenuItem mnVolverPanel;
    // End of variables declaration//GEN-END:variables
}
