/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;



/**
 *
 * @author JEFFERSON
 */
public class InterReporteCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterReporteCliente
     */
    public InterReporteCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTablaDeReportes = new javax.swing.JTable();
        btnEliminarReporteCliente = new javax.swing.JButton();
        txtIdReporteCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbxBuscarReporteVentas = new javax.swing.JComboBox<>();
        txtBuscarNombreReporte = new javax.swing.JTextField();
        btnBuscarReporteVentas = new javax.swing.JButton();
        btnRestaurarReporteCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnImprimirBoletaReport = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbTablaDeReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Factura", "ID Cliente", "Nombre Cliente", "Apellido Cliente", "DNI Cliente", "Dirección Cliente", "Teléfono Cliente", "ID Vehículo", "Placa Vehículo", "Cantidad de Servicio", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(jtbTablaDeReportes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1051, 420));

        btnEliminarReporteCliente.setBackground(new java.awt.Color(255, 102, 204));
        btnEliminarReporteCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarReporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarReporteCliente.setText("Eliminar");
        jPanel1.add(btnEliminarReporteCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel1.add(txtIdReporteCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jbxBuscarReporteVentas.setBackground(new java.awt.Color(255, 204, 51));
        jbxBuscarReporteVentas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbxBuscarReporteVentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "DNI", "Nombre", "Mes" }));

        txtBuscarNombreReporte.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        btnBuscarReporteVentas.setBackground(new java.awt.Color(204, 153, 255));
        btnBuscarReporteVentas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarReporteVentas.setText("Buscar");

        btnRestaurarReporteCliente.setBackground(new java.awt.Color(102, 255, 255));
        btnRestaurarReporteCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestaurarReporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestaurarReporteCliente.setText("Restaurar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jbxBuscarReporteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBuscarReporteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRestaurarReporteCliente)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbxBuscarReporteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReporteVentas)
                    .addComponent(btnRestaurarReporteCliente))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 650, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprimirBoletaReport.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirBoletaReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tecnico.png"))); // NOI18N
        btnImprimirBoletaReport.setBorder(null);
        btnImprimirBoletaReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirBoletaReportActionPerformed(evt);
            }
        });
        jPanel3.add(btnImprimirBoletaReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 90, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirBoletaReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirBoletaReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirBoletaReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarReporteVentas;
    public javax.swing.JButton btnEliminarReporteCliente;
    public javax.swing.JButton btnImprimirBoletaReport;
    public javax.swing.JButton btnRestaurarReporteCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jbxBuscarReporteVentas;
    public javax.swing.JTable jtbTablaDeReportes;
    public javax.swing.JTextField txtBuscarNombreReporte;
    public javax.swing.JTextField txtIdReporteCliente;
    // End of variables declaration//GEN-END:variables
}
