/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


/**
 *
 * @author JEFFERSON
 */
public class InterGestionarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterGestionarCliente
     */
    public InterGestionarCliente() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lvlIdCliente = new javax.swing.JLabel();
        txtIdGeCli = new javax.swing.JTextField();
        txtNomGeCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApGeCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDniGeCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDirGeCli = new javax.swing.JTextField();
        jlbFechaCliente = new javax.swing.JLabel();
        txtFecGeCli = new javax.swing.JTextField();
        txtCelGeCli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRestaurarTablaCliente = new javax.swing.JButton();
        cbxSelecCliente = new javax.swing.JComboBox<>();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrarClie = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 959, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 55, -1));

        lvlIdCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lvlIdCliente.setText("ID:");
        jPanel1.add(lvlIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 37, -1));
        jPanel1.add(txtIdGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 37, -1));
        jPanel1.add(txtNomGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 152, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 59, -1));
        jPanel1.add(txtApGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("DNI:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 37, -1));
        jPanel1.add(txtDniGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, -1));
        jPanel1.add(txtDirGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 160, -1));

        jlbFechaCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlbFechaCliente.setText("fecha:");
        jPanel1.add(jlbFechaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));
        jPanel1.add(txtFecGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 125, -1));
        jPanel1.add(txtCelGeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 119, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Teléfono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnRestaurarTablaCliente.setBackground(new java.awt.Color(204, 102, 255));
        btnRestaurarTablaCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestaurarTablaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestaurarTablaCliente.setText("Restaurar");

        cbxSelecCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxSelecCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID", "DNI" }));

        btnBuscarCliente.setBackground(new java.awt.Color(102, 204, 255));
        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbxSelecCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurarTablaCliente)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurarTablaCliente)
                    .addComponent(cbxSelecCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 14, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarClie.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistrarClie.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegistrarClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cli1.png"))); // NOI18N
        btnRegistrarClie.setText("Registrar");
        btnRegistrarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClieActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrarClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnModificarCliente.setBackground(new java.awt.Color(102, 255, 255));
        btnModificarCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarCliente.setText("Modificar");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        btnNuevoCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevoCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        btnEliminarCliente.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 114, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 280, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClieActionPerformed
        
    }//GEN-LAST:event_btnRegistrarClieActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCliente;
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnModificarCliente;
    public javax.swing.JButton btnNuevoCliente;
    public javax.swing.JButton btnRegistrarClie;
    public javax.swing.JButton btnRestaurarTablaCliente;
    public javax.swing.JComboBox<String> cbxSelecCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlbFechaCliente;
    public javax.swing.JLabel lvlIdCliente;
    public javax.swing.JTable tablaCliente;
    public javax.swing.JTextField txtApGeCli;
    public javax.swing.JTextField txtBuscarCliente;
    public javax.swing.JTextField txtCelGeCli;
    public javax.swing.JTextField txtDirGeCli;
    public javax.swing.JTextField txtDniGeCli;
    public javax.swing.JTextField txtFecGeCli;
    public javax.swing.JTextField txtIdGeCli;
    public javax.swing.JTextField txtNomGeCli;
    // End of variables declaration//GEN-END:variables
}
