/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


/**
 *
 * @author JEFFERSON
 */
public class InterServicioNuevo extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterServicioNuevo
     */
    public InterServicioNuevo() {
        initComponents();
        /*txtIdServ.setEnabled(false);
        servicio.mostrarServicio(jtbServicio);
        this.ordenarTablaServicios();
        txtFecSer.setEnabled(false);
        //cbxBuscSer.removeItem("kk");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdServ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomSer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesSer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreSer = new javax.swing.JTextField();
        jlabelFechaServici = new javax.swing.JLabel();
        txtFecSer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbServicio = new javax.swing.JTable();
        jlbHoraServicio = new javax.swing.JLabel();
        txtHoraServicio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnIngreServi = new javax.swing.JButton();
        btnModifiServ = new javax.swing.JButton();
        btnLimpServ = new javax.swing.JButton();
        btnEliminServ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArDescripcionServicio = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cbxBuscSer = new javax.swing.JComboBox<>();
        txtBuscaSerNom = new javax.swing.JTextField();
        btnBuscarServicio = new javax.swing.JButton();
        btnRestaurarTablaServicio = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("ID Servicio:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel1.add(txtIdServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 36, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel1.add(txtNomSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        jPanel1.add(txtDesSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jPanel1.add(txtPreSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, -1));

        jlabelFechaServici.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlabelFechaServici.setText("Fecha:");
        jPanel1.add(jlabelFechaServici, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, -1));
        jPanel1.add(txtFecSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 127, -1));

        jtbServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbServicio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 674, 350));

        jlbHoraServicio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlbHoraServicio.setText("Hora:");
        jPanel1.add(jlbHoraServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, -1, -1));
        jPanel1.add(txtHoraServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 127, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngreServi.setBackground(new java.awt.Color(255, 51, 51));
        btnIngreServi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnIngreServi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aserv.png"))); // NOI18N
        btnIngreServi.setText("Agregar");
        btnIngreServi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngreServiMouseClicked(evt);
            }
        });
        btnIngreServi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreServiActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngreServi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 114, -1));

        btnModifiServ.setBackground(new java.awt.Color(102, 255, 255));
        btnModifiServ.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModifiServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModifiServ.setText("Modificar");
        btnModifiServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifiServActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifiServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 30));

        btnLimpServ.setBackground(new java.awt.Color(255, 255, 51));
        btnLimpServ.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimpServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnLimpServ.setText("Limpiar");
        btnLimpServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpServActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 114, 30));

        btnEliminServ.setBackground(new java.awt.Color(204, 51, 255));
        btnEliminServ.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminServ.setText("Eliminar");
        btnEliminServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminServActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 114, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 270, 90));

        txtArDescripcionServicio.setColumns(20);
        txtArDescripcionServicio.setRows(5);
        jScrollPane2.setViewportView(txtArDescripcionServicio);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        cbxBuscSer.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxBuscSer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID", "Nombre", "Descripción" }));

        btnBuscarServicio.setBackground(new java.awt.Color(255, 0, 255));
        btnBuscarServicio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarServicio.setText("Buscar");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        btnRestaurarTablaServicio.setBackground(new java.awt.Color(153, 51, 255));
        btnRestaurarTablaServicio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestaurarTablaServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestaurarTablaServicio.setText("Restaurar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cbxBuscSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscaSerNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnRestaurarTablaServicio)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaurarTablaServicio)
                    .addComponent(txtBuscaSerNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBuscSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 670, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngreServiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreServiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnIngreServiActionPerformed

    private void btnModifiServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifiServActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnModifiServActionPerformed

    private void btnEliminServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminServActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminServActionPerformed

    private void btnLimpServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpServActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLimpServActionPerformed

    private void jtbServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbServicioMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtbServicioMouseClicked

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    private void btnIngreServiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngreServiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngreServiMouseClicked

    /*private void ordenarTablaServicios() {
        jtbServicio.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtbServicio.getColumnModel().getColumn(0).setResizable(false);
        jtbServicio.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtbServicio.getColumnModel().getColumn(1).setResizable(false);
        jtbServicio.getColumnModel().getColumn(2).setPreferredWidth(160);
        jtbServicio.getColumnModel().getColumn(2).setResizable(false);
        jtbServicio.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtbServicio.getColumnModel().getColumn(3).setResizable(false);
        jtbServicio.getColumnModel().getColumn(4).setPreferredWidth(90);
        jtbServicio.getColumnModel().getColumn(4).setResizable(false);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarServicio;
    public javax.swing.JButton btnEliminServ;
    public javax.swing.JButton btnIngreServi;
    public javax.swing.JButton btnLimpServ;
    public javax.swing.JButton btnModifiServ;
    public javax.swing.JButton btnRestaurarTablaServicio;
    public javax.swing.JComboBox<String> cbxBuscSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel jlabelFechaServici;
    public javax.swing.JLabel jlbHoraServicio;
    public javax.swing.JTable jtbServicio;
    public javax.swing.JTextArea txtArDescripcionServicio;
    public javax.swing.JTextField txtBuscaSerNom;
    public javax.swing.JTextField txtDesSer;
    public javax.swing.JTextField txtFecSer;
    public javax.swing.JTextField txtHoraServicio;
    public javax.swing.JTextField txtIdServ;
    public javax.swing.JTextField txtNomSer;
    public javax.swing.JTextField txtPreSer;
    // End of variables declaration//GEN-END:variables
}
