/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author JEFFERSON
 */
public class InterPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterDetalleFactura
     */
    
    public InterPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcularServicioFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRegistroCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCalcularPrecioTotalFactura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantServicios = new javax.swing.JTextField();
        txtIgvServicios = new javax.swing.JTextField();
        txtPrecioServicios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioServiciosFactura = new javax.swing.JTextField();
        btnNuevoCliente = new javax.swing.JButton();
        btnImportaDetalleFactura = new javax.swing.JButton();
        btnImportarBoletaFactura = new javax.swing.JButton();
        btnBuscarPlacaVehiculoDN = new javax.swing.JButton();
        BtnLimpiarCasilleros = new javax.swing.JButton();
        btnEliminarClienteFactura = new javax.swing.JButton();
        btnModificarClienteFactura = new javax.swing.JButton();
        txtIdDetalleFactura = new javax.swing.JTextField();
        jlblIdDetalleFactura = new javax.swing.JLabel();
        jtxDniClienteFactura = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbxCargarPlacaVehiFatura = new javax.swing.JComboBox<>();
        cbxFacturaAgregarServicio = new javax.swing.JComboBox<>();
        cbxCargarProductosFatura = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadProductoFactura = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        bcxBuscarClientesFactura = new javax.swing.JComboBox<>();
        txtBuscarClienteFactura = new javax.swing.JTextField();
        btnBuscarFactura = new javax.swing.JButton();
        btnAgruparServicios = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("DNI Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnCalcularServicioFactura.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcularServicioFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcularServicioFactura.setText("Insertar Servicio");
        btnCalcularServicioFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularServicioFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularServicioFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        tablaRegistroCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRegistroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistroClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaRegistroCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 790, 370));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcularPrecioTotalFactura.setBackground(new java.awt.Color(255, 0, 51));
        btnCalcularPrecioTotalFactura.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnCalcularPrecioTotalFactura.setText("Precio Total");
        jPanel2.add(btnCalcularPrecioTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 180, 68));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad Servicios:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IGV:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 189, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Total:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 221, -1, -1));

        txtCantServicios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jPanel2.add(txtCantServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 113, 40, -1));

        txtIgvServicios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jPanel2.add(txtIgvServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 187, 70, -1));

        txtPrecioServicios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jPanel2.add(txtPrecioServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 221, 70, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio Servicios:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 153, -1, -1));

        txtPrecioServiciosFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jPanel2.add(txtPrecioServiciosFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 153, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 290, 270));

        btnNuevoCliente.setBackground(new java.awt.Color(255, 255, 51));
        btnNuevoCliente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 119, -1));

        btnImportaDetalleFactura.setBackground(new java.awt.Color(255, 153, 51));
        btnImportaDetalleFactura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnImportaDetalleFactura.setText("Importar Boleta");
        btnImportaDetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportaDetalleFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnImportaDetalleFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 470, 180, -1));

        btnImportarBoletaFactura.setBackground(new java.awt.Color(0, 153, 0));
        btnImportarBoletaFactura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnImportarBoletaFactura.setText("Ver Boleta");
        btnImportarBoletaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarBoletaFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnImportarBoletaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 140, -1));

        btnBuscarPlacaVehiculoDN.setBackground(new java.awt.Color(255, 51, 204));
        btnBuscarPlacaVehiculoDN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarPlacaVehiculoDN.setText("Buscar");
        btnBuscarPlacaVehiculoDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaVehiculoDNActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPlacaVehiculoDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 78, -1));

        BtnLimpiarCasilleros.setBackground(new java.awt.Color(255, 204, 51));
        BtnLimpiarCasilleros.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BtnLimpiarCasilleros.setText("Limpiar");
        BtnLimpiarCasilleros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCasillerosMouseClicked(evt);
            }
        });
        BtnLimpiarCasilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarCasillerosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiarCasilleros, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 90, -1));

        btnEliminarClienteFactura.setBackground(new java.awt.Color(255, 153, 102));
        btnEliminarClienteFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarClienteFactura.setText("Eliminar");
        btnEliminarClienteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 120, -1));

        btnModificarClienteFactura.setBackground(new java.awt.Color(0, 255, 51));
        btnModificarClienteFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModificarClienteFactura.setText("Modificar");
        btnModificarClienteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 100, -1));

        txtIdDetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDetalleFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdDetalleFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 30, -1));

        jlblIdDetalleFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlblIdDetalleFactura.setText("ID:");
        jPanel1.add(jlblIdDetalleFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));
        jPanel1.add(jtxDniClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Productos:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        cbxCargarPlacaVehiFatura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxCargarPlacaVehiFatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));
        jPanel3.add(cbxCargarPlacaVehiFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        cbxFacturaAgregarServicio.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxFacturaAgregarServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "Mantenimiento", "Cambio de Puerta", "Repuestos", "Lavado" }));
        jPanel3.add(cbxFacturaAgregarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, -1));

        cbxCargarProductosFatura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxCargarProductosFatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--" }));
        jPanel3.add(cbxCargarProductosFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Nombre del Servicio:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Placa Vehículo:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Cantidad:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));
        jPanel3.add(txtCantidadProductoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 520, 60));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        bcxBuscarClientesFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bcxBuscarClientesFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "DNI", "Nombre Servicio", "Nombre Producto" }));

        btnBuscarFactura.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscarFactura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarFactura.setText("Buscar");

        btnAgruparServicios.setBackground(new java.awt.Color(204, 204, 0));
        btnAgruparServicios.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAgruparServicios.setText("Agrupar Servicios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bcxBuscarClientesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarFactura))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscarClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAgruparServicios)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcxBuscarClientesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarFactura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAgruparServicios)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 380, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void btnImportaDetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportaDetalleFacturaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnImportaDetalleFacturaActionPerformed

   
    private void btnImportarBoletaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarBoletaFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarBoletaFacturaActionPerformed

    private void BtnLimpiarCasillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarCasillerosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnLimpiarCasillerosActionPerformed

    private void BtnLimpiarCasillerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCasillerosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnLimpiarCasillerosMouseClicked

    private void btnBuscarPlacaVehiculoDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaVehiculoDNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarPlacaVehiculoDNActionPerformed

    private void txtIdDetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetalleFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetalleFacturaActionPerformed

    private void btnCalcularServicioFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularServicioFacturaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnCalcularServicioFacturaActionPerformed

    private void btnModificarClienteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteFacturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnModificarClienteFacturaActionPerformed

    private void btnEliminarClienteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteFacturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminarClienteFacturaActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void tablaRegistroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistroClienteMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablaRegistroClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnLimpiarCasilleros;
    public javax.swing.JComboBox<String> bcxBuscarClientesFactura;
    public javax.swing.JButton btnAgruparServicios;
    public javax.swing.JButton btnBuscarFactura;
    public javax.swing.JButton btnBuscarPlacaVehiculoDN;
    public javax.swing.JButton btnCalcularPrecioTotalFactura;
    public javax.swing.JButton btnCalcularServicioFactura;
    public javax.swing.JButton btnEliminarClienteFactura;
    public javax.swing.JButton btnImportaDetalleFactura;
    public javax.swing.JButton btnImportarBoletaFactura;
    public javax.swing.JButton btnModificarClienteFactura;
    public javax.swing.JButton btnNuevoCliente;
    public javax.swing.JComboBox<String> cbxCargarPlacaVehiFatura;
    public javax.swing.JComboBox<String> cbxCargarProductosFatura;
    public javax.swing.JComboBox<String> cbxFacturaAgregarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel jlblIdDetalleFactura;
    public javax.swing.JTextField jtxDniClienteFactura;
    public javax.swing.JTable tablaRegistroCliente;
    public javax.swing.JTextField txtBuscarClienteFactura;
    public javax.swing.JTextField txtCantServicios;
    public javax.swing.JTextField txtCantidadProductoFactura;
    public javax.swing.JTextField txtIdDetalleFactura;
    public javax.swing.JTextField txtIgvServicios;
    public javax.swing.JTextField txtPrecioServicios;
    public javax.swing.JTextField txtPrecioServiciosFactura;
    // End of variables declaration//GEN-END:variables

    
}
