/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


/**
 *
 * @author JEFFERSON
 */
public class InterVehiculoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterVehiculoCliente
     */
    public InterVehiculoCliente() {
        initComponents();
        /*txtVehiCli.setEnabled(false);
        txtFecClieVe.setEnabled(false);
        txtHorClieVe.setEnabled(false);
        vecontrol.mostrarVehiculoyCliente(tbVehiCli);
        this.ordenarTablaVehiculosyClientes();*/
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtModeloClieVehiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtColorrClieVehiculo = new javax.swing.JTextField();
        txtFecClieVe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculoCli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVehiCli = new javax.swing.JTextField();
        txtdniClieVehiculo = new javax.swing.JTextField();
        txtHorClieVe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPlacaClieVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbxSeleClienxBuscar = new javax.swing.JComboBox<>();
        txtBuscarNombreParaVehiculo = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        btnRestaurarVehiculo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnModificarVehiculo = new javax.swing.JButton();
        btnLimpiarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtModeloClieVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 149, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Color:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        jPanel1.add(txtColorrClieVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 149, -1));
        jPanel1.add(txtFecClieVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 149, -1));

        tablaVehiculoCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaVehiculoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVehiculoCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculoCli);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 113, 963, 450));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("ID Vehículo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("DNI Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Hora:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        jPanel1.add(txtVehiCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 88, 41, -1));
        jPanel1.add(txtdniClieVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, -1));
        jPanel1.add(txtHorClieVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 149, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Placa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel1.add(txtPlacaClieVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 149, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxSeleClienxBuscar.setBackground(new java.awt.Color(204, 204, 204));
        cbxSeleClienxBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxSeleClienxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID Vehículo", "DNI Cliente", "Placa", "Modelo" }));
        jPanel2.add(cbxSeleClienxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel2.add(txtBuscarNombreParaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 154, -1));

        btnBuscarVehiculo.setBackground(new java.awt.Color(255, 51, 51));
        btnBuscarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarVehiculo.setText("Buscar");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 117, -1));

        btnRestaurarVehiculo.setBackground(new java.awt.Color(204, 51, 255));
        btnRestaurarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRestaurarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnRestaurarVehiculo.setText("Restaurar");
        jPanel2.add(btnRestaurarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 134, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 33, 630, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarVehiculo.setBackground(new java.awt.Color(255, 255, 102));
        btnRegistrarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegistrarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnRegistrarVehiculo.setText("Ingresar");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 113, -1));

        btnModificarVehiculo.setBackground(new java.awt.Color(102, 255, 255));
        btnModificarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModificarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarVehiculo.setText("Modificar");
        btnModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnLimpiarVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimpiarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnLimpiarVehiculo.setText("Limpiar");
        btnLimpiarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 113, -1));

        btnEliminarVehiculo.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarVehiculo.setText("Eliminar");
        btnEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 114, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 267, 92));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVehiculoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnModificarVehiculoActionPerformed

    private void btnEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEliminarVehiculoActionPerformed

    private void btnLimpiarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVehiculoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLimpiarVehiculoActionPerformed

    private void tablaVehiculoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculoCliMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tablaVehiculoCliMouseClicked

    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVehiculo;
    public javax.swing.JButton btnEliminarVehiculo;
    public javax.swing.JButton btnLimpiarVehiculo;
    public javax.swing.JButton btnModificarVehiculo;
    public javax.swing.JButton btnRegistrarVehiculo;
    public javax.swing.JButton btnRestaurarVehiculo;
    public javax.swing.JComboBox<String> cbxSeleClienxBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaVehiculoCli;
    public javax.swing.JTextField txtBuscarNombreParaVehiculo;
    public javax.swing.JTextField txtColorrClieVehiculo;
    public javax.swing.JTextField txtFecClieVe;
    public javax.swing.JTextField txtHorClieVe;
    public javax.swing.JTextField txtModeloClieVehiculo;
    public javax.swing.JTextField txtPlacaClieVehiculo;
    public javax.swing.JTextField txtVehiCli;
    public javax.swing.JTextField txtdniClieVehiculo;
    // End of variables declaration//GEN-END:variables
}
