/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author JEFFERSON
 */
public class InterProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterProductos
     */
    public InterProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcionProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioUnidadProducto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioTotalProducto = new javax.swing.JTextField();
        btnCalcularProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jtxfieldHoraProducto = new javax.swing.JLabel();
        txtHoraProducto = new javax.swing.JTextField();
        jtxFechaProducto = new javax.swing.JLabel();
        txtFechaProducto = new javax.swing.JTextField();
        txtIDProducto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnInsertarProductos = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnLimpiarProducto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbxBuscarProducto = new javax.swing.JComboBox<>();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        btnActualizarProductoTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArDescripcionProducto = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 25, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, -1));
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jPanel1.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Precio/Unidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel1.add(txtPrecioUnidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 140, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Total:");

        btnCalcularProducto.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcularProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcularProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        btnCalcularProducto.setText("Calcular");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecioTotalProducto))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularProducto)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(txtPrecioTotalProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnCalcularProducto)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 780, 410));

        jtxfieldHoraProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jtxfieldHoraProducto.setText("Hora:");
        jPanel1.add(jtxfieldHoraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));
        jPanel1.add(txtHoraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, -1));

        jtxFechaProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jtxFechaProducto.setText("Fecha:");
        jPanel1.add(jtxFechaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));
        jPanel1.add(txtFechaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, -1));
        jPanel1.add(txtIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, -1));

        jPanel3.setBackground(new java.awt.Color(51, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarProductos.setBackground(new java.awt.Color(255, 204, 51));
        btnInsertarProductos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnInsertarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        btnInsertarProductos.setText("Insertar");
        jPanel3.add(btnInsertarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnModificarProducto.setBackground(new java.awt.Color(51, 255, 51));
        btnModificarProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnModificarProducto.setText("Modificar");
        jPanel3.add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        btnEliminarProducto.setBackground(new java.awt.Color(153, 102, 255));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        jPanel3.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 32));

        btnLimpiarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnLimpiarProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimpiarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnLimpiarProducto.setText("Limpiar");
        btnLimpiarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarProductoActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 114, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 600, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxBuscarProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbxBuscarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona--", "ID", "Nombre", "Descripción" }));
        jPanel4.add(cbxBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, 132, -1));
        jPanel4.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 14, 164, -1));

        btnBuscarProducto.setBackground(new java.awt.Color(204, 0, 204));
        btnBuscarProducto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuscarProducto.setText("Buscar");
        jPanel4.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 10, 118, 31));

        btnActualizarProductoTabla.setBackground(new java.awt.Color(102, 255, 255));
        btnActualizarProductoTabla.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnActualizarProductoTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Actualizar (2).png"))); // NOI18N
        btnActualizarProductoTabla.setText("Actualizar");
        jPanel4.add(btnActualizarProductoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 640, 50));

        txtArDescripcionProducto.setColumns(20);
        txtArDescripcionProducto.setRows(5);
        jScrollPane2.setViewportView(txtArDescripcionProducto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarProductoTabla;
    public javax.swing.JButton btnBuscarProducto;
    public javax.swing.JButton btnCalcularProducto;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnInsertarProductos;
    public javax.swing.JButton btnLimpiarProducto;
    public javax.swing.JButton btnModificarProducto;
    public javax.swing.JComboBox<String> cbxBuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel jtxFechaProducto;
    public javax.swing.JLabel jtxfieldHoraProducto;
    public javax.swing.JTable tablaProductos;
    public javax.swing.JTextArea txtArDescripcionProducto;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCantidadProducto;
    public javax.swing.JTextField txtDescripcionProducto;
    public javax.swing.JTextField txtFechaProducto;
    public javax.swing.JTextField txtHoraProducto;
    public javax.swing.JTextField txtIDProducto;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtPrecioTotalProducto;
    public javax.swing.JTextField txtPrecioUnidadProducto;
    // End of variables declaration//GEN-END:variables
}
